### ISSUE TITLE
failure to call v2ray core fails data statistics in Qv2ray 1.99.2.1797 on Windows

### ISSUE THREAD

**Issue by thebadgateway** [lhy0403/Qv2ray#176] opened 2019-12-10 18:12 UTC
I download files through Bittorrent and see this:

![2019-12-11_02-08-51](https://user-images.githubusercontent.com/45717841/70556346-acca6100-1bbb-11ea-9929-03acb9632878.png)

**Comment by thebadgateway** [comment] 2019-12-10 18:22
After a while, an error appeared


![2019-12-11_02-20-24](https://user-images.githubusercontent.com/45717841/70557073-1ac35800-1bbd-11ea-8002-f15abfa913a7.png)

**Comment by DuckSoft** [comment] 2019-12-15 07:25
Cannot reproduce this problem, since there's too little information. Could you please kindly give us more? For example,

* Where did you download this release?
* What's the version of your v2ray core assets?
* Have you tried rerun this without firewall or antivirus on?

Thanks for your valuable feedback.

@thebadgateway

**Comment by DuckSoft** [comment] 2019-12-15 07:30
This seems to be an issue related to gRPC communications with v2ray core.
Further investigation needed.

cc @lhy0403

**Comment by lhy0403** [comment] 2019-12-15 10:50
Yes, it's gRPC related, but I need more information to reproduce this error. Please @thebadgateway

**Comment by thebadgateway** [comment] 2019-12-15 14:23
This is Ubuntu 18.04 Qv2ray 1.99.3.1800 core: V2Ray 4.21.3
![image](https://user-images.githubusercontent.com/45717841/70864035-58dbc580-1f89-11ea-82c4-0090df322fc9.png)

**Comment by lhy0403** [comment] 2019-12-15 14:58
Possible mentioned by someone in the Telegram group earlier.

**Comment by lhy0403** [comment] 2019-12-15 15:00
@thebadgateway Just a simple single click on this text: 
![image](https://user-images.githubusercontent.com/18734999/70864605-9c84fe00-1f8e-11ea-8312-00eb67ef9ea6.png)

**Comment by lhy0403** [comment] 2019-12-15 15:00
I think we should force enable the statistics.

**Comment by lhy0403** [comment] 2019-12-27 02:14
Can this bug be re-produced in recent commits?

I cannot really do anything if it cannot be reproduced.

**Comment by thebadgateway** [comment] 2019-12-27 02:27
I also did not see this error anymore.

**Comment by lhy0403** [comment] 2019-12-27 02:29
That'll be cool and let's close this issue.
If a further issue comes again, feel free to reopen this and let us know!
😊

**Closed** 2019-12-27 02:29 UTC
Labels: Bugs, help wanted
