### ISSUE TITLE
[dev] app does not show without old configuration

### ISSUE THREAD

**Issue by thebadgateway** [lhy0403/Qv2ray#175] opened 2019-12-10 17:20 UTC
Write the location of the config file for each operating system. I can not find for macOS.

**Comment by thebadgateway** [comment] 2019-12-10 19:26
I probably found 

```
Notes: Directories that Qv2ray will search for v2ray-kernel
- Windows: C:\Users\USERNAME\.qv2ray\vcore
- macOS: /Users/USERNAME/.qv2ray/vcore
- Linux: ~/.qv2ray/vcore
```

**Comment by thebadgateway** [comment] 2019-12-10 20:03
If "Host list" is empty - app doesn't works.
Similarly, if you install the app for the first time.

**Comment by thebadgateway** [comment] 2019-12-12 17:55
Is there anybody here?

**Comment by lhy0403** [comment] 2019-12-13 00:45
Yes, but busy these days, I'll check some time after next week.
Sorry about the delay.

**Comment by thebadgateway** [comment] 2019-12-13 03:30
Maybe you can fix it this weekend?

**Comment by DuckSoft** [comment] 2019-12-15 07:14
> If "Host list" is empty - app doesn't works.
> Similarly, if you install the app for the first time.

What do you mean by app "doesn't work"? What's the exact phenomenon?

**Comment by thebadgateway** [comment] 2019-12-15 07:32
The application starts, but the main window does not appear, it seems to be minimized and cannot be expanded.

**Comment by DuckSoft** [comment] 2019-12-15 07:44
> The application starts, but the main window does not appear, it seems to be minimized and cannot be expanded.

I got it. Are you absolutely sure it's running already? If you are sure, try executing Qv2ray in terminal, and paste the output log here.

**Comment by DuckSoft** [comment] 2019-12-15 07:47
> If "Host list" is empty - app doesn't works.
> Similarly, if you install the app for the first time.

And here's another question: Will Qv2ray be working if you already have a valid existing configuration?

**Comment by thebadgateway** [comment] 2019-12-15 07:49
Yes, just add the server through the application version 1.3.8 then you can start version 1.99.3

**Comment by DuckSoft** [comment] 2019-12-15 07:54
> Yes, just add the server through the application version 1.3.8 then you can start version 1.99.3

Understood. This is weird. It will be a lot more easier if we have the log output.

**Comment by lhy0403** [comment] 2019-12-15 10:51
@thebadgateway You mean the upgrade from v1 config file (which has no connection added) will result a non-usable Qv2ray v2?

**Comment by lhy0403** [comment] 2019-12-15 10:53
Can someone help to test this in a non-macOS platform? 
I think it's a platform-independent issue.

**Comment by thebadgateway** [comment] 2019-12-15 18:50
This video showed what is happening.
https://yadi.sk/d/0z-3fRTEqoIJ4Q

**Comment by DuckSoft** [comment] 2019-12-20 21:20
> This video showed what is happening.
> https://yadi.sk/d/0z-3fRTEqoIJ4Q

Could you please kind provide with us those `Qv2ray.conf` files for inspection?
That shall help us determine where the bug is. Thank you!

**Comment by DuckSoft** [comment] 2019-12-20 22:01
On Linux I repeated the problem. Investigation in progress.

**Comment by DuckSoft** [comment] 2019-12-20 22:24
https://github.com/lhy0403/Qv2ray/blob/e864bffbbd5936336ee1ab107cf35e9c893d4698/src/ui/w_MainWindow.cpp#L219-L224

This is the root cause. If there isn't at least one node, the program will simply not show its main window. Crucial bug!

**Comment by DuckSoft** [comment] 2019-12-20 22:30
Applying patch locally and testing in progress.

**Comment by DuckSoft** [comment] 2019-12-20 22:32
Proven fixed. I'll open up a pull request to fix this bug.
Please be ready!

**Comment by DuckSoft** [comment] 2019-12-20 23:04
@thebadgateway check it out.

**Comment by thebadgateway** [comment] 2019-12-21 04:40
If you add a subscription, the application will no longer be able to start.

https://yadi.sk/i/_2nmgBNXQu-N0g

**Comment by DuckSoft** [comment] 2019-12-21 09:16
> @DuckSoft If you add a subscription, the application will no longer be able to start.
> 
> https://yadi.sk/i/_2nmgBNXQu-N0g

Check out your system tray for Qv2ray icon, and try clicking it to invoke the main window out.
The detailed reason is still in investigation.

**Comment by DuckSoft** [comment] 2019-12-21 23:35
to: @thebadgateway 

@lhy0403 have just pushed a patch for this problem. Check out the patched version and have a try!

**Comment by DuckSoft** [comment] 2019-12-22 00:06
Confirmed fixed on Arch Linux, recent build.
What about macOS? @thebadgateway 
If it's fixed, please close this issue.

**Comment by DuckSoft** [comment] 2019-12-22 05:00
Closing for now. If the problem persists, reopen this.

**Closed by DuckSoft** 2019-12-22 05:00 UTC
Labels: Bugs, help wanted
