### ISSUE TITLE
Can't reopen the main window after clicking the close button on Linux

### ISSUE THREAD

**Issue by vfreex** [lhy0403/Qv2ray#139] opened 2019-11-29 11:15 UTC
**Briefly describe this bug：**
On Linux, after closing the main window with the `X` button, I won't find a way to reopen it.
The only way I found to reopen the main window is aborting/killing the process then restarting the process.

**How can I trigger this bug：**

1. On Linux, close the main window with the `X` button.

**What is expected to happen**

I can return to the main window by either clocking the application icon or rerunning the Qv2ray process.

**Screenshots**
If appropriate, please attach some screenshots.

**System Information**

 - OS Type: Linux (Fedora 31 with GNOME and X11)
 - Built from the source or download from the release?  download from the release
 - Version string in the Preferences Window v1.99.2.918

**Other Info**

Please provide way to return to the main window after closing it.

**Comment by lhy0403** [comment] 2019-11-29 11:21
There's a known bug, @aliyuchang33, please comfirm that.

**Comment by aliyuchang33** [comment] 2019-11-29 11:33
gnome加那个顶部托盘插件，而且这玩意qt写的，本来就兼容不行

**Comment by DuckSoft** [comment] 2019-12-05 01:20
Cannot reproduce with KDE Plasma 5.17. Seems this is a problem related to 
But it may be a good advice to force a running Qv2ray to show, by rerunning Qv2ray.
---
cc @lhy0403

**Comment by lhy0403** [comment] 2019-12-05 04:07
That's a known GNOME issue initially mentioned by @aliyuchang33 to me personally, I'll do what you suggested @DuckSoft recently.

**Comment by vfreex** [comment] 2019-12-09 09:01
Thanks for checking this.
Considering GNOME is the default desktop environment of most GNU/Linux distributions, it would be nice to have this.

**Comment by lhy0403** [comment] 2019-12-09 09:46
@vfreex Sure.

**Comment by lhy0403** [comment] 2019-12-10 12:08
Fix applied, please checkout the alpha 1.1 later tonight.

**Comment by DuckSoft** [comment] 2019-12-15 07:16
Checking out commit 7ea337d1f2c54c2e962a633ea347ff229b765ef4.
Testing in progress.

**Comment by DuckSoft** [comment] 2019-12-15 07:35
Good Job. 0af45dc67827151a178e94f575ee1d375a455b8f is tested.
Now rerunning the application will wake up the existing instance.
This test is executed under KDE. I need a GNOME user to prove this fix.

cc @vfreex

**Comment by lhy0403** [comment] 2019-12-15 10:43
GNOME, please cc @aliyuchang33

**Comment by lhy0403** [comment] 2019-12-17 23:37
Fixed,closing

**Closed by lhy0403** 2019-12-17 23:37 UTC
Labels: Bugs, Upstream, f/ui/general, f/ui/mainwindow, help wanted, platform/linux
