### ISSUE TITLE
部分 linux 缺失 OpenSSL 库的问题

### ISSUE THREAD

**Issue by tyrant1024** [lhy0403/Qv2ray#65] opened 2019-09-22 08:06 UTC
找不到 OpenSSL 库
这可能是由于系统中缺少 `openssl` 包造成的，或者是 AppImage 问题。
如果您正在使用 AppImage，请反馈一个 Bug

**Comment by lhy0403** [comment] 2019-09-22 08:07
收到

**Comment by lhy0403** [comment] 2019-09-22 08:09
@1136707199 你可以提供一下 AppImage 在控制台里面的输出吗？

**Comment by lhy0403** [comment] 2019-09-23 01:40
请确定 OpenSSL 在Kali上面安装了嘛？

**Comment by cnlnn** [comment] 2019-09-24 13:13
> 找不到 OpenSSL 库
> 这可能是由于系统中缺少 `openssl` 包造成的，或者是 AppImage 问题。
> 如果您正在使用 AppImage，请反馈一个 Bug

apt install libssl1.0-dev
即可解决

**Comment by lhy0403** [comment] 2019-09-24 13:30
@1136707199 确认一下这个bug解决了吗？

**Comment by zhangxs-go** [comment] 2019-09-24 16:11
![Screenshot_20190925_000725](https://user-images.githubusercontent.com/54925441/65529509-d2cf5600-df28-11e9-902e-cd4363020371.png)
manjaro 18.1也是这样，本地版本为OpenSSL 1.1.1c，是不是版本不一致导致的？

**Comment by lhy0403** [comment] 2019-09-24 22:58
> ![Screenshot_20190925_000725](https://user-images.githubusercontent.com/54925441/65529509-d2cf5600-df28-11e9-902e-cd4363020371.png)
> manjaro 18.1也是这样，本地版本为OpenSSL 1.1.1c，是不是版本不一致导致的？

对，你的版本需要安装 openssl 1.0 的相关包，而不是 1.1

**Comment by zhangxs-go** [comment] 2019-09-25 04:31
> > ![Screenshot_20190925_000725](https://user-images.githubusercontent.com/54925441/65529509-d2cf5600-df28-11e9-902e-cd4363020371.png)
> > manjaro 18.1也是这样，本地版本为OpenSSL 1.1.1c，是不是版本不一致导致的？
> 
> 对，你的版本需要安装 openssl 1.0 的相关包，而不是 1.1

ok

**Comment by wsjtangy** [comment] 2019-09-28 15:26
> > 找不到 OpenSSL 库
> > 这可能是由于系统中缺少 `openssl` 包造成的，或者是 AppImage 问题。
> > 如果您正在使用 AppImage，请反馈一个 Bug
> 
> apt install libssl1.0-dev
> 即可解决

用此方法解决了。

**Comment by jianrry** [comment] 2019-10-02 21:31
我也遇到了同样的问题，我的操作系统是ubuntu19.04，openssl版本是1.0.2g

```
openssl version
OpenSSL 1.0.2g  1 Mar 2016
```
------

另外，我还尝试了通过`apt install openssl -y`安装最新版本的openssl ，以及本地编译安装1.0.2l版本的openssl，同样还是没有解决问题

**Comment by aliyuchang33** [comment] 2019-10-03 01:00
所需要的包不叫`openssl`，叫`openssl1.0`，装这个试试

**Comment by lhy0403** [comment] 2019-10-03 02:09
https://packages.ubuntu.com/cosmic/amd64/libssl1.0.0/download
https://packages.ubuntu.com/xenial-updates/amd64/openssl/download

These two downgrade packages make Qv2ray work after a clean install on Ubuntu 19.03, however, it may break some dependencies.

**Comment by jianrry** [comment] 2019-10-03 12:44
@lhy0403 Thanks a lot ,it has solved my problem.

```
wget http://security.ubuntu.com/ubuntu/pool/main/o/openssl1.0/libssl1.0.0_1.0.2n-1ubuntu6.2_amd64.deb && sudo dpkg -i libssl1.0.0_1.0.2n-1ubuntu6.2_amd64.deb
```

**Comment by lhy0403** [comment] 2019-10-03 12:45
好的

**Comment by aliyuchang33** [comment] 2019-10-03 15:05
你研究下这个openssl让它调用普通的openssl库呗

**Comment by lhy0403** [comment] 2019-10-03 15:05
我太南了&……

**Comment by lhy0403** [comment] 2019-10-03 15:06
这个 AppImage 里面带的理论上能行但是看起来根本不行……
现在的问题是没法找到环境测试

**Comment by lhy0403** [comment] 2019-10-04 14:53
https://github.com/openssl/openssl/issues/5042
https://bugreports.qt.io/browse/QTBUG-68971
https://gitlab.com/probono/platformissues#openssl
https://github.com/probonopd/linuxdeployqt/issues/209
https://wiki.debian.org/OpenSSL-1.1
https://lists.qt-project.org/pipermail/interest/2017-October/028512.html

**Comment by lhy0403** [comment] 2019-10-04 15:12
We choose not to fix this error since it's extremely complicated.

**Comment by lhy0403** [comment] 2019-10-04 15:18
给未来想要解决问题的所有人：
当前 Qv2ray 的 AppImage 版本需要的是 OpenSSL 1.0 ，需要进行手动安装

**Comment by jianrry** [comment] 2019-10-04 19:21
我补充一下编译安装openssl-1.0.2g的方法：

```
wget --no-check-certificate https://www.openssl.org/source/openssl-1.0.2g.tar.gz

tar -xzvf openssl-1.0.2g.tar.gz

cd openssl-1.0.2g

./config --prefix=/usr/local

 sudo make install
```
**如果你是ubuntu19.04，建议采用我上面回复的方法，不推荐编译安装。**

**Comment by Smith-Cruise** [comment] 2019-10-05 04:01
请问非 Ubuntu 的用户如何解决，我的系统是 Centos 8.

**Comment by lhy0403** [comment] 2019-10-05 07:11
> 请问非 Ubuntu 的用户如何解决，我的系统是 Centos 

https://pkgs.org/download/openssl
Pkgs.com 可以搜索到对应的 `openssl` 包
![image](https://user-images.githubusercontent.com/18734999/66251396-458acd80-e782-11e9-97a0-73a797d7c774.png)

**Comment by lhy0403** [comment] 2019-10-05 08:04
> 请问非 Ubuntu 的用户如何解决，我的系统是 Centos 8.

或者尝试一下最新一版编译出来的 AppImage 这个版本内置了 libssl.so 和 libcrypto.so
https://jenkins.lhy0403.top/job/Qv2ray-AppImage-Version1/26/

**Comment by lhy0403** [comment] 2019-10-05 08:04
> 请问非 Ubuntu 的用户如何解决，我的系统是 Centos 8.

@Smith-Cruise 或者尝试一下最新一版编译出来的 AppImage 这个版本内置了 libssl.so 和 libcrypto.so
https://jenkins.lhy0403.top/job/Qv2ray-AppImage-Version1/26/

**Comment by SiqingYu** [comment] 2019-10-06 08:31
@lhy0403

**Comment by lhy0403** [comment] 2019-10-06 08:34
Are you using the AppImage in the release or... Here: https://jenkins.lhy0403.top/job/Qv2ray-AppImage-Version1/26/

**Comment by SiqingYu** [comment] 2019-10-06 08:35
On my Debian Buster machine, I need to install these two old packages:
* Debian -- Package Download Selection -- libssl1.0-dev_1.0.2t-1~deb9u1_amd64.deb
https://packages.debian.org/stretch/amd64/libssl1.0-dev/download
* Debian -- Package Download Selection -- libssl1.0.2_1.0.2t-1~deb9u1_amd64.deb
https://packages.debian.org/stretch/amd64/libssl1.0.2/download

**Comment by lhy0403** [comment] 2019-10-06 08:35
Yes, that's super annoying and I'm trying to find a solution.

**Comment by lhy0403** [comment] 2019-10-06 08:55
> ```
> OSsl.Rq.V=OpenSSL 1.0.2g  1 Mar 2016
> OSsl.Cr.V=OpenSSL 1.0.2g  1 Mar 2016
> ```

It's not an OpenSSL issue anymore, it was my fault that I missed a `!` in the `if` statement.

**Comment by SiqingYu** [comment] 2019-10-06 09:58
@lhy0403 It's okay to make a mistake. People in the community is meant to help each other, afterall. :smiley: Kudos to you for finding the typo so quickly. :+1: 
After fixing the if statement, is libssl-dev 1.1 supposed to work?

**Comment by lhy0403** [comment] 2019-10-06 10:10
The latest release (Which will be released a few days soon) will bundle the `libssl.so` and `libcrypto.so` inside the AppImage

Which will (theoretically) need nothing to be done on your the system.

If you want to have a test, please uninstall the old packages (to make sure the `so`s are loaded from within the AppImage) and try our latest build here (it's also the place where released versions are built):
https://jenkins.lhy0403.top/blue/organizations/jenkins/Qv2ray-AppImage-Version1/activity
 - Open the link and click on the latest build from the link.
 - Then there'll be a artifact on the northeast (top-right) corner

**Comment by SiqingYu** [comment] 2019-10-06 10:22
@lhy0403 I just tried https://jenkins.lhy0403.top/job/Qv2ray-AppImage-Version1/27/artifact/build/AppDir/Qv2ray-e3cce01-x86_64.AppImage
It worked. :clap:

**Comment by lhy0403** [comment] 2019-10-06 10:31
Well it's a thing that many people `think` it's working with libssl 1.1. 
However, you should read the output by running the Appimage inside a terminal to see if it's loading a 1.1 system installed version or the Appimage-Bundled version 1.0.

I personally think this AppImage (which was built against v1.0) is not compactble with the system-wide installed 1.1 packages.

**Comment by lhy0403** [comment] 2019-10-06 10:31
Anyway, glad that you made it work!

**Comment by lhy0403** [comment] 2019-10-06 10:33
It'll be marked as solved if there're more people able to use the Appimage [here](https://jenkins.lhy0403.top/blue/organizations/jenkins/Qv2ray-AppImage-Version1/activity) without having any modifications to the system packages.

**Comment by SiqingYu** [comment] 2019-10-07 05:39
Also tested Qv2ray-AppImage-Release #69 [Jenkins]
https://jenkins.lhy0403.top/job/Qv2ray-AppImage-Release/69/ on Ubuntu 19.04. Works as intended.

**Comment by lhy0403** [comment] 2019-10-07 06:27
> Also tested Qv2ray-AppImage-Release #69 [Jenkins]
> https://jenkins.lhy0403.top/job/Qv2ray-AppImage-Release/69/ on Ubuntu 19.04. Works as intended.

Thanks for your contribution!

**Comment by lhy0403** [comment] 2019-10-08 04:56
这个问题应该在 v1.3.8 中解决了
https://github.com/lhy0403/Qv2ray/releases/tag/v1.3.8.0

**Comment by xlicz** [comment] 2019-10-10 02:57
Ubuntu 16.04 不能工作
这个软件：
https://jenkins.lhy0403.top/blue/organizations/jenkins/Qv2ray-AppImage-Version1/detail/Qv2ray-AppImage-Version1/26/artifacts/
报这个错：
![image](https://user-images.githubusercontent.com/4654912/66535544-7be29700-eb4c-11e9-808d-e4091d32ca91.png)

安装openssl 1.0.2g还是有这个问题。

使用最新的 v1.3.8.0 也有类似问题，openssl版本提示换成1.1.1

**Comment by lhy0403** [comment] 2019-10-10 03:11
你好，请不要使用 Jenkins v26 的旧版本，相反您可以尝试 https://jenkins.lhy0403.top/blue/organizations/jenkins/Qv2ray-AppImage-Release/detail/Qv2ray-AppImage-Release/104/artifacts

如果这个版本还有问题，请再下面继续回复，谢谢

**Comment by xlicz** [comment] 2019-10-10 03:18
这个版本是OK的，1.3.8.0 不OK，建议更新下。

**Comment by 1136707199** [comment] 2019-10-14 07:35
已经解决上面的问题 但似乎有了新的问题

**Comment by lhy0403** [comment] 2019-10-14 07:38
?

**Comment by lhy0403** [comment] 2019-10-14 07:39
¿

**Comment by lhy0403** [comment] 2019-10-15 10:32
> 
> 
> 已经解决上面的问题 但似乎有了新的问题

@tyrant1024 是什么问题？

**Comment by zhiai007** [comment] 2019-10-18 04:17
> 你好，请不要使用 Jenkins v26 的旧版本，相反您可以尝试 https://jenkins.lhy0403.top/blue/organizations/jenkins/Qv2ray-AppImage-Release/detail/Qv2ray-AppImage-Release/104/artifacts

这资源不存在了嘛？

**Comment by lhy0403** [comment] 2019-10-18 04:20
> 
> 
> > 你好，请不要使用 Jenkins v26 的旧版本，相反您可以尝试 https://jenkins.lhy0403.top/blue/organizations/jenkins/Qv2ray-AppImage-Release/detail/Qv2ray-AppImage-Release/104/artifacts
> 
> 这资源不存在了嘛？

@zhiai007 https://jenkins.lhy0403.top/job/Qv2ray-AppImage-Release/104/artifact/build/AppDir/

**Comment by lhy0403** [comment] 2019-10-26 12:34
这个烦人的问题终于在 https://github.com/lhy0403/Qv2ray/commit/2fcd32e31e1a4865bb3eea940cd20fc0df2c18e1 被修复，将于 2.0 版本正式应用修改
感谢大家的支持，issue 将被关闭
如果还有相关 openssl 的问题，请到 #69 讨论

**Closed by lhy0403** 2019-10-26 12:34 UTC
Labels: Bugs, Upstream, help wanted, platform/linux, t/packaging

**Comment by lhy0403** [comment] 2019-10-26 12:36
v1 后续版本（如果有）将使用这里的 AppImage
https://jenkins.lhy0403.top/job/Qv2ray-AppImage-Release/lastSuccessfulBuild/artifact/
